# Generated by Django 3.1.7 on 2021-03-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_twitter', '0002_auto_20210311_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='like_count',
        ),
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
