# Generated by Django 3.1.7 on 2021-03-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_twitter', '0003_auto_20210311_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
