# Generated by Django 3.1.7 on 2021-03-14 20:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_twitter', '0004_auto_20210314_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
